### ISSUE TITLE
IEC 104 parser does not compile for the latest versions of Zeek and Spicy

### ISSUE THREAD

**Issue by georgemakrakis** [DINA-community/ot-parsers#1]
Hello,

First thank you for providing those parsers!

The issue that I encounter is that Spicy compilation fails with the following errors, when I try to build it with **Zeek 6.1.1 and Spicy v1.9.0**.

```
root@zeek-6-1-1:/ot-parsers/IEC60870-5-104# spicyz -o iec104.hlto ./analyzer/iec60870_5_104.spicy ./analyzer/iec60870_5_104.evt ./analyzer/zeek_iec60870_5_104.spicy
[error] /ot-parsers/IEC60870-5-104/analyzer/iec60870_5_104.spicy:1118:12-1128:2: bitfield item 'name' shadows unit field
[error] /ot-parsers/IEC60870-5-104/analyzer/iec60870_5_104.spicy:1132:12-1142:2: bitfield item 'name' shadows unit field
[error] /ot-parsers/IEC60870-5-104/analyzer/iec60870_5_104.spicy:1074:12-1084:2: bitfield item 'size' shadows unit field
[error] <Spicy Plugin for Zeek>: aborting after errors
```

For **Zeek 6.0.0 and Spicy v1.8.1** it works like a charm. I think that something has changed to the way anonymous fields work in the those later versions. 

If you want to avoid those crashes maybe a check for the Spicy version (see below) would be sufficient until the bug is fixed. 

```
@if SPICY_VERSION <= <version-number>
....
@endif
```

**Comment by JPLettuce** [comment]
Fixed for IEC60870-5-104 in #5 . Closing this issue ahead of the fixing merge as #4 , addressing all current parsers, is still open.
